server:
  port: 8081
  servlet:
    context-path: /api/v1
spring:
  application:
    name: microservice
  datasource:
    url: jdbc:mysql://localhost:3306/microservice
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect    
    hibernate:
      ddl-auto: validate
      type:
        descriptor:
          sql:
            BasicBinder: TRACE
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl  
  h2:
    console:
      enabled: true
      path: /h2-console
  flyway:
    enable: true
    baseline-on-migrate: true
    validate-on-migrate: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2