spring:
  application:
    name: configuration_server
    label: main
  cloud:
    config:
      server:
        git:
          uri: https://github.com/GTTo/project_architecture.git
          username: cbevia@gmail.com
          password: R4b4nit0s
          search-paths:
            - "config-repo/{application}/{profile}"
          default-label: main

server:
  port: 8888
