spring:
  application:
    name: configuration_server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/GTTo/geekshubs_config_server.git
          username:
          password:

server:
  port: 8888
